import {
  EDGE_CASE_INSTRUCTION,
  HIGH_LEVEL_PROMPT,
  LOW_LEVEL_PROMPT,
  VISUAL_SEMANTICS_INSTRUCTION,
} from "./prompts";

export const COMPLETE_LOW_LEVEL_PROMPT = `
${LOW_LEVEL_PROMPT}

${VISUAL_SEMANTICS_INSTRUCTION}
`;

export const COMPLETE_LOW_LEVEL_WITH_EDGE_CASES_PROMPT = `
${LOW_LEVEL_PROMPT}

${EDGE_CASE_INSTRUCTION}

${VISUAL_SEMANTICS_INSTRUCTION}
`;

export const COMPLETE_HIGH_LEVEL_PROMPT = `
${HIGH_LEVEL_PROMPT}

${VISUAL_SEMANTICS_INSTRUCTION}
`;
